remote_theme: just-the-docs
title: Paweł Sobótka
description: Feel free to bookmark this to keep eye on my project
twitter_username: StaryWandal
github_username: majsterklepka
email: starywandal@onet.pl
repository: majsterklepka/majsterklepka.github.io
permalink: title

defaults:
  - scope:
      path: "assets/image"
    values:
      image: true

github:
  repository_url: https://github.com/majsterklepka/majsterklepka.github.io

favicon: favicon.ico

markdown: kramdown

plugins_dir:
 - github-pages

plugins:
        - "jekyll-github-metadata"    

# Exclude from processing

exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
