theme: jekyll-theme-midnight
title: Majster Klepka
description: Blog osobisty, programowanie, Linux, Radioamatorstwo, Open Source, Makers. Poczuj się wolny, dodaj do zakładek tę stronę i obserwuj moje projekty! 
github_username: majsterklepka
email: starywandal@onet.pl
repository: majsterklepka/majsterklepka.github.io
permalink: pretty
image: /images/fluidicon.png

defaults:
  - scope:
      path: "assets/images"
    values:
      image: true

github:
  repository_url: https://github.com/majsterklepka

favicon: favicon.png

markdown: kramdown
tag_page_layout: tags_page
tag_page_dir: tags
tag_feed_layout: tags_feed
tag_feed_dir: tags
tag_permalink_style: pretty

plugins_dir:
 - github-pages

plugins:
  - jekyll-github-metadata  
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-hashtags	
  - jekyll-tagging  

# Exclude from processing

# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
