theme: jekyll-theme-midnight
title: Majster Klepka
name: Majster Klepka
description: Blog osobisty, programowanie, Linux, Radioamatorstwo, Open Source, Makers. Poczuj się wolny, dodaj do zakładek tę stronę i obserwuj moje projekty! 
github_username: majsterklepka
email: starywandal@onet.pl
repository: majsterklepka/majsterklepka.github.io
permalink: pretty
logo: /images/majsterklepka.jpg
author: StaryWandal
url: https://majsterklepka.github.io
tags: true

defaults:
  - scope:
      path: "assets/images"
    values:
      image: true

github:
  repository_url: https://github.com/majsterklepka

paginate: 5
paginate_path: "/home/page:num/"
posts_number: 4

google_analytics: UA-146473711-1

markdown: kramdown
tag_page_layout: tags_page
tag_page_dir: tags
tag_feed_layout: tags_feed
tag_feed_dir: tags
tag_permalink_style: pretty

feed:
  path: /rss/feed.xml

manifest_name: Majster Klepka
manifest_short_name: Majster Klepka 
manifest_lang: pl
manifest_background_color: white
manifest_display: standalone

facebook:
  publisher: https://www.facebook.com/agrestmen

twitter:
  username: StaryWandal
  card: summary_large_image

social:
  name: Paweł Sobótka
  links:
    - https://www.facebook.com/agrestmen
    - https://github.com/majsterklepka
    - https://www.twitter.com/StaryWandal	

plugins_dir:
 - github-pages

plugins:
  - jekyll-github-metadata  
  - jekyll-feed
  - jekyll-sitemap	
  - jekyll-tagging
  - jekyll-seo-tag
  - jekyll-favicon  
  - jekyll-paginate

# Exclude from processing

# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
