theme: jekyll-theme-merlot
title: Majster Klepka
description: Feel free to bookmark this to keep eye on my project
email: starywandal@onet.pl
twitter_username: StaryWandal
github_username: majsterklepka
permalink: title

github:
  repository_url: https://github.com/majsterklepka

defaults:
  - scope:
      path: "assets/image"
    values:
      image: true

markdown: kramdown
plugins:
 - jekyll-feed
 - jekyll-sitemap

# Exclude from processing

# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
