theme: jekyll-theme-merlot
title: Majster Klepka
description: Feel free to bookmark this to keep eye on my project
twitter_username: StaryWandal
github_username: majsterklepka
repository: majsterklepka/majsterklepka.github.io
permalink: title

defaults:
  - scope:
      path: "assets/image"
    values:
      image: true
   
favicon: favicon.ico

github:
  repository_url: https://github.com/majsterklepka

markdown: kramdown

plugins_dir:
 - github-pages

# Exclude from processing

# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
